### ISSUE TITLE
Firefox Compatibility

### ISSUE THREAD

**Issue by togekk** [mbasso/wasm-worker#3]
**General Information**

- [x] Bug
- [ ] Improvement
- [ ] Feature
- [ ] Other

**Description**
Wasm-worker won't start in Firefox. Shows error messages.

![error messages](https://imgur.com/aYc0ksO.jpg)

**Steps to reproduce**
1. Clone [this example repo](https://github.com/togekk/wasm-worker-test.git) to local
2. Run `yarn`
3. Run `yarn run serve` to start server
4. Open Firefox and open url [http://localhost:1234](http://localhost:1234)
5. Press F12 to see the error messages

**Versions**

- wasm-worker: 0.3.1

**Comment by mbasso** [comment]
Hi @togekk,
thank you for opening this issue with the example repo and for your intereste in this project. I really appreciate it! 😄
I've just published a new version of wasm-worker that solves this problem. Just try to update to version 0.3.2.
Let me know if it works fine and I can close this issue!

**Comment by togekk** [comment]
Everything looks perfect now! Thanks :D
